import type { WidgetDefinition } from "@/widgets/types";
import type { WidgetCategory, WidgetKey } from "@/types/dashboard";

export const widgetDefinitions: WidgetDefinition[] = [
  {
    key: "current-temperature",
    name: "Current Temperature",
    description: "Current and feels-like temperature.",
    category: "weather",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Temperature",
  },
  {
    key: "current-conditions",
    name: "Current Conditions",
    description: "Current sky and precipitation conditions.",
    category: "weather",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Conditions",
  },
  {
    key: "rain-chance",
    name: "Rain Chance",
    description: "Upcoming precipitation probability.",
    category: "weather",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Rain Chance",
  },
  {
    key: "hourly-forecast",
    name: "Hourly Forecast",
    description: "A compact hourly weather timeline.",
    category: "weather",
    sourceKind: "weather-location",
    defaultSize: "large",
    defaultTitle: "Hourly Forecast",
  },
  {
    key: "daily-forecast",
    name: "Daily Forecast",
    description: "Upcoming daily highs, lows, and conditions.",
    category: "weather",
    sourceKind: "weather-location",
    defaultSize: "large",
    defaultTitle: "Daily Forecast",
  },
  {
    key: "wind-speed",
    name: "Wind Speed",
    description: "Current sustained wind speed.",
    category: "wind",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Wind Speed",
  },
  {
    key: "wind-gusts",
    name: "Wind Gusts",
    description: "Current and expected wind gusts.",
    category: "wind",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Wind Gusts",
  },
  {
    key: "wind-direction",
    name: "Wind Direction",
    description: "Compass direction and bearing.",
    category: "wind",
    sourceKind: "weather-location",
    defaultSize: "small",
    defaultTitle: "Wind Direction",
  },
  {
    key: "wind-forecast",
    name: "Wind Forecast",
    description: "Hourly wind speed, gust, and direction changes.",
    category: "wind",
    sourceKind: "weather-location",
    defaultSize: "large",
    defaultTitle: "Wind Forecast",
  },
  {
    key: "next-high-tide",
    name: "Next High Tide",
    description: "Time and predicted height of the next high tide.",
    category: "tides",
    sourceKind: "tide-station",
    defaultSize: "small",
    defaultTitle: "Next High Tide",
  },
  {
    key: "next-low-tide",
    name: "Next Low Tide",
    description: "Time and predicted height of the next low tide.",
    category: "tides",
    sourceKind: "tide-station",
    defaultSize: "small",
    defaultTitle: "Next Low Tide",
  },
  {
    key: "tide-status",
    name: "Tide Status",
    description: "Whether the tide is rising, falling, or near a turn.",
    category: "tides",
    sourceKind: "tide-station",
    defaultSize: "small",
    defaultTitle: "Tide Status",
  },
  {
    key: "tide-timeline",
    name: "Tide Timeline",
    description: "Upcoming high and low tide events.",
    category: "tides",
    sourceKind: "tide-station",
    defaultSize: "large",
    defaultTitle: "Tide Timeline",
  },
  {
    key: "tide-station",
    name: "Tide Station",
    description: "Station identity and distance from the fishing location.",
    category: "tides",
    sourceKind: "tide-station",
    defaultSize: "medium",
    defaultTitle: "Tide Station",
  },
  {
    key: "wave-height",
    name: "Wave Height",
    description: "Current significant wave height.",
    category: "waves",
    sourceKind: "marine-location",
    defaultSize: "small",
    defaultTitle: "Wave Height",
  },
  {
    key: "wave-direction",
    name: "Wave Direction",
    description: "Direction waves are arriving from.",
    category: "waves",
    sourceKind: "marine-location",
    defaultSize: "small",
    defaultTitle: "Wave Direction",
  },
  {
    key: "wave-period",
    name: "Wave Period",
    description: "Time between successive wave crests.",
    category: "waves",
    sourceKind: "marine-location",
    defaultSize: "small",
    defaultTitle: "Wave Period",
  },
  {
    key: "swell-information",
    name: "Swell Information",
    description: "Swell height, direction, and period.",
    category: "waves",
    sourceKind: "marine-location",
    defaultSize: "medium",
    defaultTitle: "Swell",
  },
  {
    key: "moon-phase",
    name: "Moon Phase",
    description: "Current lunar phase.",
    category: "moon-sun",
    sourceKind: "astronomy-location",
    defaultSize: "small",
    defaultTitle: "Moon Phase",
  },
  {
    key: "moon-illumination",
    name: "Moon Illumination",
    description: "Visible percentage of the Moon.",
    category: "moon-sun",
    sourceKind: "astronomy-location",
    defaultSize: "small",
    defaultTitle: "Moon Illumination",
  },
  {
    key: "moonrise-moonset",
    name: "Moonrise & Moonset",
    description: "Local Moon rise and set times.",
    category: "moon-sun",
    sourceKind: "astronomy-location",
    defaultSize: "medium",
    defaultTitle: "Moonrise & Moonset",
  },
  {
    key: "sunrise-sunset",
    name: "Sunrise & Sunset",
    description: "Local daylight times.",
    category: "moon-sun",
    sourceKind: "astronomy-location",
    defaultSize: "medium",
    defaultTitle: "Sunrise & Sunset",
  },
];

export const categoryLabels: Record<WidgetCategory, string> = {
  weather: "Weather",
  wind: "Wind",
  tides: "Tides",
  waves: "Waves",
  "moon-sun": "Moon & Sun",
};

export const categoryOrder: WidgetCategory[] = [
  "weather",
  "wind",
  "tides",
  "waves",
  "moon-sun",
];

export function getWidgetDefinition(key: WidgetKey): WidgetDefinition {
  const definition = widgetDefinitions.find((item) => item.key === key);

  if (!definition) {
    throw new Error(`Unknown widget: ${key}`);
  }

  return definition;
}
